function [dx, y] = DoublePendMotor(t,x,V_in,c1,l1,b1,m1,J1,c2,g,b2,m2,J2,k_gear,k_mot,R_mot,L_mot,varargin)
%DOUBLEPENDMOTOR
%    QSOL = DOUBLEPENDMOTOR(THETA1,DTHETA1,THETA2,DTHETA2,DC_MOT,V_IN,C1,L1,B1,M1,J1,C2,G,B2,M2,J2,K_GEAR,K_MOT,R_MOT,L_MOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Sep-2021 11:24:07

V_in = -V_in;

theta1 = x(1);
dtheta1 = x(2);
theta2 = x(3);
dtheta2 = x(4);
dc_mot = x(5);

t2 = cos(theta2);
t3 = sin(theta1);
t4 = sin(theta2);
t5 = theta1+theta2;
t6 = c1.^2;
t7 = c2.^2;
t8 = c2.^3;
t9 = dtheta1.^2;
t10 = dtheta2.^2;
t11 = l1.^2;
t12 = m2.^2;
t13 = J1.*J2;
t15 = J2.*b1.*dtheta1;
t16 = J2.*b2.*dtheta2;
t18 = J2.*dc_mot.*k_gear.*k_mot;
t14 = t2.^2;
t17 = sin(t5);
t19 = -t15;
t20 = J2.*m1.*t6;
t21 = J1.*m2.*t7;
t22 = J2.*m2.*t11;
t23 = b1.*dtheta1.*m2.*t7;
t24 = b2.*dtheta2.*m2.*t7;
t25 = J2.*c1.*g.*m1.*t3;
t26 = J2.*g.*l1.*m2.*t3;
t27 = dc_mot.*k_gear.*k_mot.*m2.*t7;
t29 = m1.*m2.*t6.*t7;
t30 = J2.*c2.*l1.*m2.*t4.*t9;
t31 = J2.*c2.*l1.*m2.*t4.*t10;
t32 = J2.*c2.*dtheta1.*dtheta2.*l1.*m2.*t4.*2.0;
t33 = c1.*g.*m1.*m2.*t3.*t7;
t34 = t7.*t11.*t12;
t35 = g.*l1.*t3.*t7.*t12;
t36 = l1.*t4.*t8.*t9.*t12;
t37 = l1.*t4.*t8.*t10.*t12;
t38 = dtheta1.*dtheta2.*l1.*t4.*t8.*t12.*2.0;
t28 = -t23;
t39 = t14.*t34;
t40 = g.*l1.*t2.*t7.*t12.*t17;
t41 = -t39;
t42 = -t40;
t43 = t13+t20+t21+t22+t29+t34+t41;
t44 = 1.0./t43;
qSol = [t44.*(t16+t18+t19+t24+t25+t26+t27+t28+t30+t31+t32+t33+t35+t36+t37+t38+t42+t2.*t4.*t9.*t34+b2.*c2.*dtheta2.*l1.*m2.*t2);-t44.*(t16+t18+t19+t24+t25+t26+t27+t28+t30+t31+t32+t33+t35+t36+t37+t38+t42+J1.*b2.*dtheta2+b2.*dtheta2.*m1.*t6+b2.*dtheta2.*m2.*t11+t2.*t4.*t9.*t34.*2.0+t2.*t4.*t10.*t34-J1.*c2.*g.*m2.*t17+dtheta1.*dtheta2.*t2.*t4.*t34.*2.0-c2.*g.*t11.*t12.*t17+c2.*l1.^3.*t4.*t9.*t12+J1.*c2.*l1.*m2.*t4.*t9-b1.*c2.*dtheta1.*l1.*m2.*t2+b2.*c2.*dtheta2.*l1.*m2.*t2.*2.0-c2.*g.*m1.*m2.*t6.*t17+c2.*g.*t2.*t3.*t11.*t12+c2.*dc_mot.*k_gear.*k_mot.*l1.*m2.*t2+c2.*l1.*m1.*m2.*t4.*t6.*t9+c1.*c2.*g.*l1.*m1.*m2.*t2.*t3);-(-V_in+R_mot.*dc_mot+dtheta1.*k_gear.*k_mot)./L_mot];

dx = [x(2); 
     qSol(1);
     x(4);
     qSol(2:3)];

y = [x(1); x(3)];

