function f_nonlin_dt = nonlin_state(x,V_in)
%NONLIN_STATE
%    F_NONLIN_DT = NONLIN_STATE(V_IN,x(2),x(4),G,x(1),x(3))

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Oct-2021 12:19:02
g = 9.81;

f_nonlin_dt = [x(2)./1.0e+2+x(1);
                x(2).*5.589397636773543e-1;
                x(4)./1.0e+2+x(3);
                x(4).*9.992542834184246e-1-x(2).^2.*sin(x(3)).*1.163827932628266e-2+g.*sin(x(1)+x(3)).*1.199822610956975e-1+(cos(x(3)).*6.79e-4+5.834195768670185e-4).*(V_in.*2.947102727195652e+2+x(2).*4.410602363226457e+1).*1.714032301367108e+1];
end